version: '3.4'

services:

  postgresql_server:
    build: ./database/
    image: denishuaman/postgresql_ventas:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ventas
    volumes:
      - my-data-postgresql:/var/lib/postgresql
    restart: on-failure
    networks:
      - backend

  apiventa:
    build: ./apiVenta/
    image: denishuaman/api-venta:latest
    environment:
      - hostapi=http://apipersona:8081
      - host=postgresql_server
      - port=5432
      - database=ventas
      - username=postgres
      - password=root
    depends_on:
      - postgresql_server
    restart: on-failure
    entrypoint: dockerize -wait tcp://postgresql_server:5432 -timeout 10m java -jar /app.jar
    networks:
      - backend

  apipersona:
    build: ./apiPersona/
    image: denishuaman/api-persona:latest
    environment:
      - host=postgresql_server
      - port=5432
      - database=ventas
      - username=postgres
      - password=root
    depends_on:
      - postgresql_server
    restart: on-failure
    entrypoint: dockerize -wait tcp://postgresql_server:5432 -timeout 10m java -jar /app.jar
    networks:
      - backend

  proxy:
    build: ./proxy-backend/
    image: denishuaman/proxy-venta:latest
    ports:
      - "80:80"
    depends_on: 
      - apipersona
      - apiventa
    restart: on-failure
    networks:
      - backend

volumes:
  my-data-postgresql:
networks:
  backend: