server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    show-sql: true
    hibernate:      ddl-auto: none    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host}:${port}/${database}
    username: ${username}
    password: ${password}