server:
  port: 8082

restful:
  timeout: 10000

url:
  api:
    persona:
      buscar-por-dni: ${hostapi}/api/personas/buscar

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host}:${port}/${database}
    username: ${username}
    password: ${password}