server:
  port: 8082

restful:
  timeout: 10000

url:
  api:
    persona:
      buscar-por-dni: ${hostapi}/api/personas/buscar

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false
    username: ${username}
    password: ${password}
